<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Generates database schema documentation as Markdown.
 * Outputs: table name, columns, types, indexes, foreign keys.
 */
class GenerateSchemaDocsCommand extends Command
{
    protected $signature = 'docs:schema {--output=docs/database-schema.md : Output file path}';

    protected $description = 'Generate database schema documentation in Markdown';

    public function handle(): int
    {
        $tables = $this->getTables();

        $md = "# Muhasebi Database Schema\n\n";
        $md .= "> Auto-generated on " . now()->toDateString() . "\n\n";
        $md .= "## Table of Contents\n\n";

        foreach ($tables as $table) {
            $md .= "- [{$table}](#{$table})\n";
        }

        $md .= "\n---\n\n";

        foreach ($tables as $table) {
            $this->info("  Documenting {$table}...");

            $md .= "## {$table}\n\n";

            // Columns
            $columns = Schema::getColumns($table);
            $md .= "| Column | Type | Nullable | Default |\n";
            $md .= "|--------|------|----------|---------|\n";

            foreach ($columns as $col) {
                $nullable = ($col['nullable'] ?? false) ? 'Yes' : 'No';
                $default = $col['default'] ?? '-';
                $type = $col['type_name'] ?? $col['type'] ?? 'unknown';
                $name = $col['name'] ?? 'unknown';

                $md .= "| `{$name}` | {$type} | {$nullable} | {$default} |\n";
            }

            // Indexes
            try {
                $indexes = Schema::getIndexes($table);
                if (! empty($indexes)) {
                    $md .= "\n**Indexes:**\n";
                    foreach ($indexes as $index) {
                        $cols = implode(', ', $index['columns'] ?? []);
                        $type = ($index['unique'] ?? false) ? 'UNIQUE' : 'INDEX';
                        $name = $index['name'] ?? '';
                        $md .= "- `{$name}` ({$type}) on ({$cols})\n";
                    }
                }
            } catch (\Throwable) {
                // Some drivers don't support getIndexes
            }

            // Foreign keys
            try {
                $foreignKeys = Schema::getForeignKeys($table);
                if (! empty($foreignKeys)) {
                    $md .= "\n**Foreign Keys:**\n";
                    foreach ($foreignKeys as $fk) {
                        $localCols = implode(', ', $fk['columns'] ?? []);
                        $foreignTable = $fk['foreign_table'] ?? 'unknown';
                        $foreignCols = implode(', ', $fk['foreign_columns'] ?? []);
                        $name = $fk['name'] ?? '';
                        $md .= "- `{$name}`: ({$localCols}) → {$foreignTable}({$foreignCols})\n";
                    }
                }
            } catch (\Throwable) {
                // Some drivers don't support getForeignKeys
            }

            $md .= "\n---\n\n";
        }

        // Summary
        $md .= "## Summary\n\n";
        $md .= "- **Total tables:** " . count($tables) . "\n";
        $md .= "- **Database:** " . config('database.default') . "\n";
        $md .= "- **Generated by:** `php artisan docs:schema`\n";

        $outputPath = $this->option('output');
        $fullPath = base_path($outputPath);

        $dir = dirname($fullPath);
        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        file_put_contents($fullPath, $md);

        $this->info("Schema docs generated: {$outputPath} (" . count($tables) . " tables)");

        return self::SUCCESS;
    }

    private function getTables(): array
    {
        $tables = Schema::getTables();

        return collect($tables)
            ->pluck('name')
            ->filter(fn ($t) => ! in_array($t, ['migrations', 'sqlite_sequence']))
            ->sort()
            ->values()
            ->toArray();
    }
}
