<?php

declare(strict_types=1);

/**
 * Role-based permissions map.
 *
 * SuperAdmin bypasses all checks (via Gate::before).
 * Client is confined to portal routes (via ClientPortalMiddleware).
 * Only tenant-level roles are mapped here.
 *
 * Naming convention:
 *  - `view_<leaf>` — granular per-nav-link visibility (one per sidebar leaf,
 *                    matches `staff-nav.ts` permissions). Frontend uses these
 *                    to show/hide UI; safe to grant freely.
 *  - `manage_<feature>` — gate write actions (create / update / delete /
 *                          send / post). Backend route middleware uses these.
 *
 * Default role mappings:
 *  - admin    → every view_* and every manage_*
 *  - accountant → most view_* (financial scope) + most manage_* (no admin
 *                 actions like team / subscription / landing / webhooks)
 *  - auditor  → every view_* (read-only across the app) + manage_documents
 *               (so they can attach evidence to working papers)
 *
 * To restrict a specific user beyond their role's defaults, use Spatie's
 * direct user-permission grant/revoke (independent of role assignments).
 */
return [
    'admin' => [
        // ---- view (nav visibility) — FULL ACCESS
        'view_dashboard',
        'view_notifications',
        'view_activity_log',
        'view_audit',
        'view_clients',
        'view_invoices',
        'view_recurring_invoices',
        'view_payments',
        'view_credit_notes',
        'view_collections',
        'view_vendors',
        'view_bills',
        'view_bill_payments',
        'view_expenses',
        'view_expense_reports',
        'view_bank_accounts',
        'view_bank_reconciliation',
        'view_bank_connections',
        'view_fx_revaluation',
        'view_chart_of_accounts',
        'view_journal_entries',
        'view_recurring_journal_entries',
        'view_fiscal_calendar',
        'view_cost_centers',
        'view_budgets',
        'view_inventory_products',
        'view_inventory_categories',
        'view_stock_movements',
        'view_stock_alerts',
        'view_fixed_assets',
        'view_asset_categories',
        'view_depreciation',
        'view_asset_disposals',
        'view_vat_returns',
        'view_wht',
        'view_corporate_tax',
        'view_eta',
        'view_eta_item_codes',
        'view_employees',
        'view_payroll',
        'view_payslips',
        'view_salary_components',
        'view_loans',
        'view_leave',
        'view_attendance',
        'view_social_insurance',
        'view_engagements',
        'view_deliverables',
        'view_working_papers',
        'view_timesheets',
        'view_timer',
        'view_reports',
        'view_custom_reports',
        'view_scheduled_reports',
        'view_anomalies',
        'view_approvals',
        'view_alerts',
        'view_documents',
        'view_import',
        'view_ecommerce',
        'view_messaging',
        'view_team',
        'view_onboarding',
        'view_subscription',
        'view_company',
        'view_currencies',
        'view_webhooks',
        'view_landing',
        'view_settings',

        // ---- manage (write actions)
        'manage_team',
        'manage_settings',
        'manage_subscription',
        'manage_clients',
        'invite_client_portal',
        'manage_accounts',
        'manage_journal_entries',
        'post_journal_entries',
        'manage_invoices',
        'send_invoices',
        'manage_payments',
        'manage_documents',
        'manage_eta',
        'manage_timesheets',
        'approve_timesheets',
        'manage_payroll',
        'manage_employees',
        'manage_landing_page',
        'manage_onboarding',
        'manage_vendors',
        'manage_bills',
        'manage_fixed_assets',
        'manage_expenses',
        'manage_collections',
        'manage_cost_centers',
        'manage_tax',
        'manage_inventory',
        'manage_integrations',
        'manage_engagements',
        'manage_approvals',
        'manage_alerts',
        'manage_reports',
    ],

    'accountant' => [
        // ---- view (nav visibility) — broad financial scope, no admin areas
        'view_dashboard',
        'view_notifications',
        'view_activity_log',
        'view_clients',
        'view_invoices',
        'view_recurring_invoices',
        'view_payments',
        'view_credit_notes',
        'view_collections',
        'view_vendors',
        'view_bills',
        'view_bill_payments',
        'view_expenses',
        'view_expense_reports',
        'view_bank_accounts',
        'view_bank_reconciliation',
        'view_bank_connections',
        'view_fx_revaluation',
        'view_chart_of_accounts',
        'view_journal_entries',
        'view_recurring_journal_entries',
        'view_fiscal_calendar',
        'view_cost_centers',
        'view_budgets',
        'view_inventory_products',
        'view_inventory_categories',
        'view_stock_movements',
        'view_stock_alerts',
        'view_fixed_assets',
        'view_asset_categories',
        'view_depreciation',
        'view_asset_disposals',
        'view_vat_returns',
        'view_wht',
        'view_corporate_tax',
        'view_eta',
        'view_eta_item_codes',
        'view_employees',
        'view_payroll',
        'view_payslips',
        'view_salary_components',
        'view_loans',
        'view_leave',
        'view_attendance',
        'view_social_insurance',
        'view_engagements',
        'view_deliverables',
        'view_working_papers',
        'view_timesheets',
        'view_timer',
        'view_reports',
        'view_custom_reports',
        'view_scheduled_reports',
        'view_anomalies',
        'view_approvals',
        'view_alerts',
        'view_documents',
        'view_import',
        'view_messaging',
        // not granted: view_team, view_subscription, view_company, view_currencies,
        //              view_webhooks, view_landing, view_settings, view_ecommerce,
        //              view_audit, view_onboarding

        // ---- manage (write actions)
        'manage_clients',
        'manage_payroll',
        'manage_accounts',
        'manage_journal_entries',
        'manage_invoices',
        'send_invoices',
        'manage_payments',
        'manage_documents',
        'manage_eta',
        'manage_timesheets',
        'manage_vendors',
        'manage_bills',
        'manage_fixed_assets',
        'manage_expenses',
        'manage_collections',
        'manage_cost_centers',
        'manage_tax',
        'manage_inventory',
        'manage_integrations',
        'manage_engagements',
        'manage_approvals',
        'manage_reports',
    ],

    'auditor' => [
        // ---- view (nav visibility) — read-only access across the firm
        'view_dashboard',
        'view_notifications',
        'view_activity_log',
        'view_audit',
        'view_clients',
        'view_invoices',
        'view_recurring_invoices',
        'view_payments',
        'view_credit_notes',
        'view_collections',
        'view_vendors',
        'view_bills',
        'view_bill_payments',
        'view_expenses',
        'view_expense_reports',
        'view_bank_accounts',
        'view_bank_reconciliation',
        'view_chart_of_accounts',
        'view_journal_entries',
        'view_recurring_journal_entries',
        'view_fiscal_calendar',
        'view_cost_centers',
        'view_budgets',
        'view_inventory_products',
        'view_inventory_categories',
        'view_stock_movements',
        'view_stock_alerts',
        'view_fixed_assets',
        'view_asset_categories',
        'view_depreciation',
        'view_asset_disposals',
        'view_vat_returns',
        'view_wht',
        'view_corporate_tax',
        'view_eta',
        'view_employees',
        'view_payroll',
        'view_payslips',
        'view_engagements',
        'view_deliverables',
        'view_working_papers',
        'view_reports',
        'view_custom_reports',
        'view_scheduled_reports',
        'view_anomalies',
        'view_documents',

        // ---- manage (write actions) — auditors get document-attach only
        'manage_documents',
    ],
];
